name: ai-pneumonia-classifier
channels:
  - conda-forge
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - absl-py=2.1.0
  - astunparse=1.6.3
  - blas=1.0
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - c-ares=1.34.5
  - ca-certificates=2025.2.25
  - cached-property=1.5.2
  - certifi=2025.4.26
  - charset-normalizer=3.3.2
  - contourpy=1.3.1
  - cycler=0.11.0
  - expat=2.6.4
  - flatbuffers=24.12.23
  - fonttools=4.55.3
  - freetype=2.13.3
  - gast=0.5.3
  - giflib=5.2.2
  - google-pasta=0.2.0
  - grpcio=1.67.1
  - h5py=3.14.0
  - hdf5=1.14.6
  - icu=75.1
  - idna=3.7
  - keras=3.6.0
  - kiwisolver=1.4.8
  - krb5=1.21.3
  - lcms2=2.17
  - lerc=4.0.0
  - libabseil=20240722.0
  - libaec=1.1.3
  - libcurl=8.14.1
  - libcxx=20.1.6
  - libdeflate=1.22
  - libedit=3.1.20230828
  - libev=4.33
  - libexpat=2.6.4
  - libffi=3.4.4
  - libfreetype=2.13.3
  - libfreetype6=2.13.3
  - libgfortran=5.0.0
  - libgfortran5=14.2.0
  - libgrpc=1.67.1
  - libjpeg-turbo=3.1.0
  - libnghttp2=1.64.0
  - libopenblas=0.3.29
  - libpng=1.6.47
  - libprotobuf=5.28.3
  - libre2-11=2024.07.02
  - libsqlite=3.50.1
  - libssh2=1.11.1
  - libtiff=4.7.0
  - libwebp-base=1.5.0
  - libxcb=1.17.0
  - libzlib=1.3.1
  - llvm-openmp=14.0.6
  - markdown=3.8
  - markdown-it-py=2.2.0
  - markupsafe=3.0.2
  - matplotlib=3.10.0
  - matplotlib-base=3.10.0
  - mdurl=0.1.0
  - ml_dtypes=0.4.1
  - namex=0.0.7
  - ncurses=6.4
  - numpy=2.2.5
  - numpy-base=2.2.5
  - openjpeg=2.5.3
  - openssl=3.5.0
  - opt_einsum=3.3.0
  - optree=0.14.1
  - packaging=24.2
  - pillow=11.2.1
  - pip=25.1
  - protobuf=5.28.3
  - pthread-stubs=0.3
  - pygments=2.19.1
  - pyparsing=3.2.0
  - pysocks=1.7.1
  - python=3.12.2
  - python-dateutil=2.9.0post0
  - python-flatbuffers=24.3.25
  - python_abi=3.12
  - re2=2024.07.02
  - readline=8.2
  - requests=2.32.3
  - rich=13.9.4
  - setuptools=72.1.0
  - six=1.17.0
  - snappy=1.2.1
  - sqlite=3.22.0
  - tensorboard=2.18.0
  - tensorboard-data-server=0.7.0
  - tensorflow=2.18.0
  - tensorflow-base=2.18.0
  - tensorflow-estimator=2.18.0
  - termcolor=2.1.0
  - tk=8.6.13
  - tornado=6.5.1
  - typing-extensions=4.12.2
  - typing_extensions=4.12.2
  - tzdata=2025b
  - unicodedata2=15.1.0
  - urllib3=2.3.0
  - werkzeug=3.1.3
  - wheel=0.45.1
  - wrapt=1.17.0
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xz=5.6.4
  - zlib=1.3.1
  - zstd=1.5.7
